"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import {
  ArrowRight, BarChart3, Bell, BrainCircuit, BriefcaseBusiness, Check,
  ChevronDown, CircleCheck, Clock3, FileSearch, Menu, MessageSquareText,
  Search, ShieldCheck, Sparkles, Target, Users, X, Zap,
} from "lucide-react";

const features = [
  { icon: BrainCircuit, title: "AI candidate matching", text: "Score candidates against the skills, experience and requirements that matter for each role.", className: "md:col-span-2" },
  { icon: FileSearch, title: "Automated screening", text: "Turn a large applicant pool into a focused shortlist without repetitive manual review.", className: "" },
  { icon: BrainCircuit, title: "Recruiter copilot", text: "Ask AI to find candidates, summarize profiles, draft outreach and surface risks.", className: "" },
  { icon: Users, title: "Recruitment CRM", text: "Keep jobs, candidates, applications, interviews and conversations in one workspace.", className: "" },
  { icon: BarChart3, title: "Hiring analytics", text: "See pipeline health, hiring velocity, source performance and decision trends.", className: "md:col-span-2" },
];

const workflow = [
  ["01", "Create the role", "Add a job description or let AI turn a short hiring brief into a structured role."],
  ["02", "Find and screen", "TalentFlow organizes candidates and applies consistent screening criteria."],
  ["03", "Understand fit", "Review match scores, evidence, strengths and gaps before moving candidates forward."],
  ["04", "Move to hire", "Coordinate interviews, collect feedback and keep the entire hiring team aligned."],
];

const faqs = [
  ["What is TalentFlow AI?", "TalentFlow AI is a recruitment platform designed to help teams source, screen, match and manage candidates from one intelligent workspace."],
  ["Does AI make the final hiring decision?", "No. TalentFlow provides structured insights, recommendations and automation while recruiters and hiring managers remain responsible for final decisions."],
  ["Can recruitment agencies use TalentFlow?", "Yes. The workflow is designed for internal talent teams, growing businesses and agencies managing multiple roles and candidate pipelines."],
  ["Can I connect TalentFlow to my existing process?", "The platform is designed to complement existing hiring workflows. Integrations and ATS/HRIS connections can be added as the product evolves."],
];

function Logo() {
  return <a href="#top" className="flex items-center gap-2.5 font-bold tracking-tight text-slate-950"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600 text-white shadow-lg shadow-blue-600/25"><Zap size={18} fill="currentColor" /></span><span className="text-lg">TalentFlow<span className="text-blue-600"> AI</span></span></a>;
}

function DashboardMockup() {
  const candidates = [
    ["SJ", "Sarah Johnson", "Senior Product Designer", "96%", "bg-violet-100 text-violet-700"],
    ["DM", "David Morgan", "Product Designer", "93%", "bg-blue-100 text-blue-700"],
    ["AK", "Amina Khan", "UX Designer", "89%", "bg-emerald-100 text-emerald-700"],
  ];
  return <div className="dashboard-shadow overflow-hidden rounded-[28px] border border-white/70 bg-white">
    <div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 sm:px-5 sm:py-4"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-blue-600 text-white"><Zap size={14} fill="currentColor" /></span><div><p className="text-xs font-bold">TalentFlow AI</p><p className="text-[9px] text-slate-400">Recruitment command center</p></div></div><div className="flex items-center gap-2 text-[10px] text-slate-500"><span className="h-2 w-2 rounded-full bg-emerald-500" /> AI active <span className="ml-2 h-7 w-7 rounded-full bg-slate-200" /></div></div>
    <div className="grid min-h-[400px] grid-cols-[150px_1fr]"><aside className="hidden border-r border-slate-100 bg-slate-50/80 p-4 sm:block"><p className="px-2 text-[9px] font-bold uppercase tracking-wider text-slate-400">Workspace</p><div className="mt-3 space-y-1 text-[10px] font-semibold">{["Overview", "Jobs", "Candidates", "Applications", "Interviews", "Analytics"].map((item, i) => <div key={item} className={`rounded-lg px-3 py-2.5 ${i === 0 ? "bg-blue-50 text-blue-700" : "text-slate-500"}`}>{item}</div>)}</div><div className="mt-14 rounded-2xl bg-slate-950 p-3 text-white"><Sparkles size={14} className="text-blue-300" /><p className="mt-2 text-[10px] font-semibold">AI insight</p><p className="mt-1 text-[9px] leading-4 text-slate-400">14 high-fit candidates are ready for review.</p></div></aside><main className="min-w-0 p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] text-slate-400">Open position</p><h3 className="mt-1 text-sm font-bold sm:text-base">Senior Product Designer</h3></div><button className="rounded-lg bg-slate-950 px-3 py-2 text-[9px] font-bold text-white">View job</button></div><div className="mt-5 grid grid-cols-3 gap-2 sm:gap-3">{[["128", "Candidates"], ["14", "Shortlisted"], ["5", "Interviews"]].map(([number, label]) => <div key={label} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-lg font-black">{number}</p><p className="mt-1 text-[9px] text-slate-400">{label}</p></div>)}</div><div className="mt-5 rounded-2xl border border-slate-100 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold">Top AI matches</p><span className="text-[10px] font-semibold text-blue-600">View all</span></div><div className="space-y-2">{candidates.map(([initials, name, role, score, badge]) => <div key={name} className="flex items-center gap-3 rounded-xl bg-slate-50 p-2.5"><span className={`grid h-9 w-9 place-items-center rounded-full text-[9px] font-black ${badge}`}>{initials}</span><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-bold">{name}</p><p className="truncate text-[9px] text-slate-400">{role}</p></div><div className="text-right"><p className="text-[11px] font-black text-emerald-600">{score}</p><p className="text-[8px] text-slate-400">match</p></div></div>)}</div></div></main></div>
  </div>;
}

export default function Home() {
  const [menu, setMenu] = useState(false);
  const [faq, setFaq] = useState<number | null>(0);
  return <div id="top" className="overflow-hidden bg-slate-50 text-slate-950">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/70 bg-white/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-7 text-sm font-semibold text-slate-500 md:flex"><a href="#platform" className="transition hover:text-slate-950">Platform</a><a href="#features" className="transition hover:text-slate-950">Features</a><a href="#how-it-works" className="transition hover:text-slate-950">How it works</a><a href="#pricing" className="transition hover:text-slate-950">Pricing</a></nav><div className="hidden items-center gap-3 md:flex"><a href="#contact" className="px-3 py-2 text-sm font-semibold text-slate-600">Sign in</a><a href="#contact" className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-slate-950/10 transition hover:-translate-y-0.5 hover:bg-blue-600">Get started <ArrowRight className="ml-1 inline" size={14} /></a></div><button aria-label="Toggle navigation" className="md:hidden" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button></div>{menu && <div className="border-t border-slate-100 bg-white px-5 py-5 md:hidden"><div className="flex flex-col gap-4 text-sm font-semibold"><a href="#platform" onClick={() => setMenu(false)}>Platform</a><a href="#features" onClick={() => setMenu(false)}>Features</a><a href="#how-it-works" onClick={() => setMenu(false)}>How it works</a><a href="#pricing" onClick={() => setMenu(false)}>Pricing</a><a href="#contact" onClick={() => setMenu(false)} className="rounded-xl bg-slate-950 px-4 py-3 text-center text-white">Get started</a></div></div>}</header>

    <main>
      <section className="hero-grid relative px-5 pb-20 pt-32 lg:pb-28 lg:pt-40"><div className="pointer-events-none absolute left-1/2 top-10 h-[500px] w-[700px] -translate-x-1/2 rounded-full bg-blue-500/10 blur-[100px]" /><div className="relative mx-auto max-w-7xl"><div className="mx-auto max-w-4xl text-center"><motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mx-auto inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-4 py-2 text-xs font-bold text-blue-700 shadow-sm"><Sparkles size={13} /> The intelligent hiring workspace</motion.div><motion.h1 initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="mt-6 text-5xl font-black leading-[0.98] tracking-[-0.055em] sm:text-6xl lg:text-7xl">Hire smarter.<br /><span className="gradient-text">Build stronger teams.</span></motion.h1><motion.p initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-500 sm:text-lg">Source, screen, match and manage exceptional talent with AI. TalentFlow turns recruiting from a pile of applications into a clear, intelligent workflow.</motion.p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="#contact" className="rounded-xl bg-blue-600 px-6 py-3.5 text-sm font-bold text-white shadow-xl shadow-blue-600/20 transition hover:-translate-y-0.5 hover:bg-blue-700">Start hiring with AI <ArrowRight className="ml-1 inline" size={15} /></a><a href="#platform" className="rounded-xl border border-slate-200 bg-white px-6 py-3.5 text-sm font-bold text-slate-800 shadow-sm transition hover:bg-slate-50">See how it works</a></div><div className="mt-6 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs font-medium text-slate-400"><span>✓ AI matching</span><span>✓ Automated screening</span><span>✓ Recruitment CRM</span><span>✓ Human-in-the-loop</span></div></div><motion.div initial={{ opacity: 0, y: 40 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.18 }} className="mx-auto mt-14 max-w-5xl lg:mt-20"><DashboardMockup /></motion.div></div></section>

      <section className="border-y border-slate-200 bg-white px-5 py-10"><div className="mx-auto max-w-5xl"><p className="text-center text-[10px] font-bold uppercase tracking-[0.22em] text-slate-400">A better operating system for hiring</p><div className="mt-7 grid grid-cols-2 gap-7 text-center sm:grid-cols-4"><div><p className="text-3xl font-black">3×</p><p className="mt-1 text-xs text-slate-400">faster workflows</p></div><div><p className="text-3xl font-black">85%</p><p className="mt-1 text-xs text-slate-400">less manual screening</p></div><div><p className="text-3xl font-black">24/7</p><p className="mt-1 text-xs text-slate-400">AI assistance</p></div><div><p className="text-3xl font-black">1</p><p className="mt-1 text-xs text-slate-400">connected workspace</p></div></div></div></section>

      <section id="platform" className="px-5 py-24 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[0.9fr_1.1fr]"><div><span className="section-label">Why TalentFlow</span><h2 className="section-title">Recruiting should feel like a system, not a spreadsheet.</h2><p className="section-copy">Too many applications, disconnected tools and hours spent doing work that software should handle. TalentFlow brings the process together and gives your team an AI layer for the decisions that matter.</p><div className="mt-8 space-y-5">{[[Search, "Find signal in the noise", "Surface the candidates most aligned with your actual requirements."], [Clock3, "Automate the busywork", "Reduce repetitive screening, coordination and follow-up tasks."], [CircleCheck, "Make better decisions", "See structured evidence, strengths and gaps before the next interview."]].map(([Icon, title, text]) => { const I = Icon as typeof Search; return <div key={title as string} className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><I size={19} /></span><div><h3 className="font-bold">{title as string}</h3><p className="mt-1 text-sm leading-6 text-slate-500">{text as string}</p></div></div>; })}</div></div><div className="rounded-[30px] border border-slate-200 bg-white p-3 shadow-2xl shadow-slate-900/5 sm:p-5"><div className="rounded-[24px] bg-slate-950 p-5 text-white sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-500">AI command center</p><h3 className="mt-1 text-xl font-black">Your hiring, in one view.</h3></div><span className="rounded-xl bg-white/10 p-2.5"><BrainCircuit size={20} className="text-blue-300" /></span></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/[0.06] p-4"><p className="text-xs text-slate-400">Match quality</p><p className="mt-2 text-3xl font-black">94%</p><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full w-[94%] rounded-full bg-blue-400" /></div></div><div className="rounded-2xl bg-white/[0.06] p-4"><p className="text-xs text-slate-400">Hiring velocity</p><p className="mt-2 text-3xl font-black">+38%</p><p className="mt-2 text-[10px] text-emerald-300">↑ illustrative trend</p></div></div><div className="mt-3 rounded-2xl bg-white/[0.06] p-4"><div className="flex justify-between text-xs"><span className="text-slate-300">Candidate pipeline</span><span className="text-blue-300">Live view</span></div><div className="mt-5 flex items-end gap-1.5">{[42, 60, 48, 76, 63, 86, 71, 96, 80, 102].map((height, index) => <div key={index} className="flex-1 rounded-t bg-blue-400/80" style={{ height }} />)}</div></div></div></div></div></section>

      <section id="features" className="bg-white px-5 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><span className="section-label">One platform</span><h2 className="section-title">Everything your recruiting team needs to move faster.</h2><p className="section-copy">TalentFlow combines automation, intelligence and candidate management into a single workflow built for modern hiring teams.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, title, text, className }) => <motion.div key={title} whileHover={{ y: -4 }} className={`rounded-3xl border border-slate-200 bg-slate-50 p-7 transition hover:border-blue-200 hover:bg-white hover:shadow-xl hover:shadow-blue-950/5 ${className}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-white text-blue-600 shadow-sm"><Icon size={20} /></span><h3 className="mt-6 text-lg font-black">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p><span className="mt-6 inline-flex items-center text-xs font-bold text-blue-600">Explore capability <ArrowRight size={13} className="ml-1" /></span></motion.div>)}</div></div></section>

      <section id="how-it-works" className="px-5 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><div className="text-center"><span className="section-label">How it works</span><h2 className="section-title mx-auto max-w-3xl">From job brief to confident shortlist in four simple steps.</h2></div><div className="mt-14 grid gap-4 md:grid-cols-4">{workflow.map(([number, title, text]) => <div key={number} className="relative rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><span className="text-4xl font-black tracking-tight text-blue-100">{number}</span><h3 className="mt-5 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><div className="mt-6 h-1 w-12 rounded-full bg-blue-600" /></div>)}</div></div></section>

      <section className="px-5 pb-24 lg:pb-32"><div className="mx-auto grid max-w-7xl items-center gap-10 overflow-hidden rounded-[32px] bg-slate-950 p-7 text-white sm:p-10 lg:grid-cols-[1fr_0.9fr] lg:p-14"><div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-wider text-blue-200"><Sparkles size={12} /> Recruiter copilot</span><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">Ask TalentFlow to do the heavy lifting.</h2><p className="mt-5 max-w-xl leading-7 text-slate-400">Give your recruiters an AI teammate that can search your talent pool, summarize candidates, explain match quality and prepare the next action.</p><div className="mt-8 space-y-3"><div className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><MessageSquareText size={18} className="mt-0.5 shrink-0 text-blue-300" /><p className="text-sm text-slate-300">“Find the 10 strongest candidates for our Python role and explain why they match.”</p></div><div className="flex items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.04] p-4"><Target size={18} className="mt-0.5 shrink-0 text-violet-300" /><p className="text-sm text-slate-300">“Which shortlisted candidates have the biggest experience gaps?”</p></div></div></div><div className="rounded-3xl border border-white/10 bg-white/[0.06] p-5"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-600"><BrainCircuit size={17} /></span><div><p className="text-xs font-bold">TalentFlow Copilot</p><p className="text-[9px] text-slate-500">Analyzing candidate pool</p></div><span className="ml-auto h-2 w-2 rounded-full bg-emerald-400" /></div><div className="mt-5 space-y-3"><div className="rounded-2xl bg-white/[0.06] p-4"><p className="text-[9px] font-bold uppercase tracking-wider text-blue-300">Recommendation</p><p className="mt-2 text-sm leading-6 text-slate-200">Three candidates stand out based on Python, FastAPI and production-scale experience.</p></div>{[["Amina Khan", "96% match"], ["David Morgan", "93% match"], ["Sarah Johnson", "89% match"]].map(([name, score]) => <div key={name} className="flex items-center justify-between rounded-xl bg-white/[0.04] px-4 py-3"><span className="text-xs font-semibold text-slate-300">{name}</span><span className="text-xs font-black text-emerald-300">{score}</span></div>)}</div></div></div></section>

      <section className="border-y border-slate-200 bg-white px-5 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><div className="grid gap-8 lg:grid-cols-3"><div className="rounded-3xl bg-blue-600 p-8 text-white"><p className="text-xs font-bold uppercase tracking-wider text-blue-100">Designed for trust</p><h3 className="mt-4 text-2xl font-black">AI assists. Humans decide.</h3><p className="mt-3 text-sm leading-6 text-blue-100">Keep recruiters and hiring managers in control with transparent, reviewable recommendations.</p><ShieldCheck className="mt-10" size={32} /></div><div className="rounded-3xl border border-slate-200 bg-slate-50 p-8"><Bell className="text-blue-600" size={22} /><h3 className="mt-6 text-xl font-black">Stay on top of every candidate</h3><p className="mt-2 text-sm leading-6 text-slate-500">Keep applications, interview feedback and next steps visible to everyone involved.</p></div><div className="rounded-3xl border border-slate-200 bg-slate-50 p-8"><BriefcaseBusiness className="text-blue-600" size={22} /><h3 className="mt-6 text-xl font-black">Built around the role</h3><p className="mt-2 text-sm leading-6 text-slate-500">Match candidates against what the job actually needs instead of relying on keyword searches alone.</p></div></div></div></section>

      <section id="pricing" className="px-5 py-24 lg:py-32"><div className="mx-auto max-w-7xl"><div className="text-center"><span className="section-label">Simple pricing</span><h2 className="section-title mx-auto max-w-2xl">Start small. Scale your hiring operation.</h2><p className="mx-auto mt-4 max-w-xl text-slate-500">Use these launch prices as a starting point while TalentFlow moves toward production billing.</p></div><div className="mx-auto mt-12 grid max-w-5xl gap-5 lg:grid-cols-3"><PricingCard name="Starter" price="$49" text="For small teams hiring occasionally." items={["1 active job", "AI candidate matching", "Basic screening", "Candidate pipeline"]} /><PricingCard featured name="Growth" price="$149" text="For teams hiring every month." items={["10 active jobs", "AI recruiter copilot", "Advanced screening", "Interview workflow", "Hiring analytics"]} /><PricingCard name="Enterprise" price="Custom" text="For high-volume hiring teams and agencies." items={["Unlimited workflows", "Custom roles & permissions", "Advanced analytics", "Integrations", "Priority support"]} /></div></div></section>

      <section className="bg-white px-5 py-24 lg:py-32"><div className="mx-auto max-w-3xl"><div className="text-center"><span className="section-label">FAQ</span><h2 className="section-title">Questions, answered.</h2></div><div className="mt-10 divide-y divide-slate-200 rounded-3xl border border-slate-200 bg-white">{faqs.map(([question, answer], index) => <div key={question}><button className="flex w-full items-center justify-between gap-6 px-6 py-5 text-left" onClick={() => setFaq(faq === index ? null : index)}><span className="text-sm font-bold">{question}</span><ChevronDown size={17} className={`shrink-0 text-slate-400 transition ${faq === index ? "rotate-180" : ""}`} /></button>{faq === index && <div className="px-6 pb-5 text-sm leading-6 text-slate-500">{answer}</div>}</div>)}</div></div></section>

      <section id="contact" className="px-5 py-20"><div className="relative mx-auto max-w-6xl overflow-hidden rounded-[34px] bg-blue-600 px-6 py-16 text-center text-white sm:px-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,.18),transparent_30%),radial-gradient(circle_at_80%_80%,rgba(99,102,241,.35),transparent_35%)]" /><div className="relative"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-4 py-2 text-xs font-bold"><Sparkles size={13} /> The future of recruiting starts here</span><h2 className="mx-auto mt-6 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Your next great hire is already out there.</h2><p className="mx-auto mt-5 max-w-2xl text-blue-100">Give your team the intelligence and automation to find them faster.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><a href="mailto:hello@talentflow.ai" className="rounded-xl bg-white px-6 py-3.5 text-sm font-black text-blue-700 transition hover:bg-blue-50">Talk to TalentFlow <ArrowRight className="ml-1 inline" size={15} /></a><a href="#platform" className="rounded-xl border border-white/20 bg-white/10 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white/15">Explore platform</a></div></div></div></section>
    </main>

    <footer className="border-t border-slate-200 bg-white px-5 py-10"><div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><Logo /><div className="flex flex-wrap gap-5 text-xs font-semibold text-slate-400"><a href="#platform" className="hover:text-slate-700">Platform</a><a href="#features" className="hover:text-slate-700">Features</a><a href="#pricing" className="hover:text-slate-700">Pricing</a><a href="#contact" className="hover:text-slate-700">Contact</a></div><p className="text-xs text-slate-400">© 2026 TalentFlow AI. Built for modern hiring teams.</p></div></footer>
  </div>;
}

function PricingCard({ name, price, text, items, featured = false }: { name: string; price: string; text: string; items: string[]; featured?: boolean }) {
  return <div className={`rounded-3xl border p-7 ${featured ? "border-blue-600 bg-slate-950 text-white shadow-2xl shadow-blue-950/15" : "border-slate-200 bg-white"}`}><div className="flex items-center justify-between"><h3 className="font-black">{name}</h3>{featured && <span className="rounded-full bg-blue-600 px-2.5 py-1 text-[9px] font-bold uppercase tracking-wider">Popular</span>}</div><p className={`mt-2 text-sm ${featured ? "text-slate-400" : "text-slate-500"}`}>{text}</p><p className="mt-7 text-4xl font-black">{price}<span className={`text-sm font-medium ${featured ? "text-slate-500" : "text-slate-400"}`}>{price !== "Custom" ? "/month" : ""}</span></p><a href="#contact" className={`mt-7 block rounded-xl px-4 py-3 text-center text-sm font-bold ${featured ? "bg-blue-600 text-white hover:bg-blue-500" : "bg-slate-950 text-white hover:bg-blue-600"}`}>{price === "Custom" ? "Contact sales" : "Get started"}</a><div className="mt-7 space-y-3">{items.map(item => <div key={item} className="flex gap-2.5 text-sm"><Check size={16} className="mt-0.5 shrink-0 text-blue-500" /><span className={featured ? "text-slate-300" : "text-slate-600"}>{item}</span></div>)}</div></div>;
}
